include:
  - project: 'dhei/teams/io/templates/gitlab-pipelines'
    file: '/docker/gitlab-ci.docker.yml'
    ref: develop

variables:
  MTR_TARGET_IMAGE:   iris
  MTR_TARGET_TAG:     $CI_COMMIT_REF_NAME
  MTR_BASE_IMAGE_TAG: '16.1.1'

stages:
- prepare
- dockerize
- publish

.add_alpine_packages: &add_alpine_packages |
  apk add --no-cache bash

default:
  tags: [ "otc_run_docker_m" ]

# jobs

build:extensions:
  image: openjdk:15-jdk-alpine
  stage: prepare
  script:
  - *add_alpine_packages
  - cd extensions && ./build.sh
  - cd ./../themes && chmod +x build.sh && ./build.sh
  artifacts:
    paths:
    - "$CI_PROJECT_DIR/providers/"
    - "$CI_PROJECT_DIR/themez/"
  
build:image:
  extends: .docker:build:tif-with-dependencies
  stage: dockerize
  variables:
    CUSTOM_DOCKER_BUILD_OPTIONS: "--build-arg BASE_IMAGE_TAG=$MTR_BASE_IMAGE_TAG"
  dependencies:
  - build:extensions

build:image-devops:
  extends: .docker:build:tif-public-to-mtr-devops-internal
  stage: dockerize
  variables:
    CUSTOM_DOCKER_BUILD_OPTIONS: "--build-arg BASE_IMAGE_TAG=$MTR_BASE_IMAGE_TAG"
  dependencies:
  - build:extensions
  
publish:image:
  extends: .docker:mirror:tif-to-tif-public
  stage: publish
  only:
    refs:
      - tags
  dependencies:
    - build:image

copy:image-from-tif-public-to-mtr-common:
  extends: .docker:mirror:tif-public-to-mtr-devops-common
  stage: prepare
  when: manual
  variables:
    MTR_TIF_PUBLIC_SRC_IMAGE: keycloak
    MTR_TIF_PUBLIC_SRC_TAG: 9.0.3
    MTR_TARGET_IMAGE: keycloak
    MTR_TARGET_TAG: 9.0.3
