# SPDX-FileCopyrightText: 2025 Deutsche Telekom AG
#
# SPDX-License-Identifier: CC0-1.0

include:
  - project: 'dhei/teams/galatea/products/iris-keycloak/cicd'
    file: 'docker.gitlab-ci.yml'
    ref: 'main'
